### ISSUE TITLE
Issue with LunaUnitFrames.

### ISSUE THREAD

**Issue by ghost** [Schaka/EnemyBuffTimersVanilla#2]
Hello,
1. I have recently downloaded the lunaunitframes branch of this addon in order to make it work with LunaUnitFrames addon. Most of the time it works flawlessly. However when my hunter is far from the target the timer usually doesn't appear. Is it caused by the large distance (it's not that large since I'm still able to attack those mobs)? Is there any way to fix this?
2. Moreover every few minutes the timers don't appear on the buff/debuff bar of my target but in the middle of my character (like on this screenshot: http://i.imgur.com/SlIp0GE.jpg) - sometimes many different timer on top of each other.. Do you know what could be causing this issue?
3. Is it safe to merge the lunaunitframe branch with the updated spell list from the master branch?

Cheers,
Matt

**Comment by Schaka** [comment]
I haven't actually figured out what causes the frames to appear in the middle of the screen. I haven't developed this addon in years. 

Merging the spell list is fine though.

**Comment by ghost** [comment]
Alright, thanks for the info.
