### ISSUE TITLE
hide numeric countdown?

### ISSUE THREAD

**Issue by ShaunDreclin** [Schaka/EnemyBuffTimersVanilla#3]
I prefer just having the cooldown sweep, could you add an option to hide the numbers on the icons? Having trouble finding it in the code to disable it myself

**Comment by Schaka** [comment]
You could just delete Cooldown.lua

I don't maintain this addon anymore. EnemyFrames (you can find it on the Kronos forums) has replaced all the necessary functionality. EBTV was originally just meant as a quick backport of one of my TBC addons.

**Comment by ShaunDreclin** [comment]
Aha thanks!
